import { VanillaExtractPlugin } from "@vanilla-extract/webpack-plugin";
import HtmlWebpackPlugin from "html-webpack-plugin";
import MiniCssExtractPlugin from "mini-css-extract-plugin";
import { createRequire } from "module";
import { dirname, resolve } from "path";
import { fileURLToPath } from "url";

const __dirnameCustom = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

export const baseConfig = {
  target: "web",
  entry: "./src/index.tsx",

  module: {
    rules: [
      {
        test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: require.resolve("css-loader"),
            options: {
              url: false, // Required as image imports should be handled via JS/TS import statements
            },
          },
        ],
      },

      {
        test: /\.tsx?$/,
        use: "ts-loader",
        exclude: /node_modules/,
      },
    ],
  },

  plugins: [
    new HtmlWebpackPlugin({
      template: "./src/index.html",
    }),
    new VanillaExtractPlugin(),
    new MiniCssExtractPlugin(),
  ],

  output: {
    filename: "[name].bundle.js",
    path: resolve(__dirnameCustom, "build"),
    clean: true,
    hashFunction: "xxhash64",
  },

  resolve: {
    extensions: [".tsx", ".ts", ".js", ".html"],
    extensionAlias: {
      ".js": [".tsx", ".ts", ".js"],
    },
  },
};
